// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDflp9Hw9r-8-ETFH7EnM7z0i8c_ufnEkY',
    appId: '1:994256679586:web:ef0f41a1c6b114f2ac9dfb',
    messagingSenderId: '994256679586',
    projectId: 'sdd-go-app',
    authDomain: 'sdd-go-app.firebaseapp.com',
    storageBucket: 'sdd-go-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-cu1orB0HLZO3bWfqh2QJYkVVywAI8h8',
    appId: '1:994256679586:android:48874ea682cc4997ac9dfb',
    messagingSenderId: '994256679586',
    projectId: 'sdd-go-app',
    storageBucket: 'sdd-go-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPgtWgBp8Urb2D3okmTIBGENFVY0JuO40',
    appId: '1:994256679586:ios:e1fec16fde501380ac9dfb',
    messagingSenderId: '994256679586',
    projectId: 'sdd-go-app',
    storageBucket: 'sdd-go-app.appspot.com',
    iosClientId: '994256679586-kdhs34h977eeqh6ne0lvnge8mlr2j1jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sddGo',
  );
}
